const programsData = [
  {
    id: 1,
    name: "Discovery Summer Science Camp",
    type: "Summer Camp",
    organization: "Discovery Science Center",
    address: "2500 N Main St",
    city: "Springfield",
    state: "IL",
    zip: "62701",
    phone: "(217) 555-0101",
    email: "camps@discoveryscience.org",
    website: "https://example.com/discoveryscience",
    gradesMin: "K",
    gradesMax: "5",
    ageMin: 5,
    ageMax: 11,
    cost: 250,
    costPeriod: "week",
    scholarshipAvailable: true,
    hours: "8:00 AM – 4:00 PM",
    daysOffered: "Mon–Fri",
    sessionType: "Summer",
    subjects: ["STEM", "Science", "Technology"],
    description: "Hands-on science experiments, robotics, and engineering challenges for curious young minds. Weekly sessions throughout summer.",
    indoorOutdoor: "Both",
    transportation: false,
    mealsProvided: true,
    acceptingRegistration: true
  },
  {
    id: 2,
    name: "Arts & Crafts Summer Camp",
    type: "Summer Camp",
    organization: "Community Arts Center",
    address: "150 Oak Ave",
    city: "Riverside",
    state: "IL",
    zip: "60546",
    phone: "(708) 555-0202",
    email: "info@communityarts.org",
    website: "https://example.com/communityarts",
    gradesMin: "1",
    gradesMax: "8",
    ageMin: 6,
    ageMax: 14,
    cost: 175,
    costPeriod: "week",
    scholarshipAvailable: true,
    hours: "9:00 AM – 3:00 PM",
    daysOffered: "Mon–Fri",
    sessionType: "Summer",
    subjects: ["Arts", "Music", "Drama"],
    description: "Explore painting, sculpture, music, and theater in a supportive, creative environment. All skill levels welcome.",
    indoorOutdoor: "Indoor",
    transportation: false,
    mealsProvided: false,
    acceptingRegistration: true
  },
  {
    id: 3,
    name: "YMCA After School Program",
    type: "Afterschool Care",
    organization: "YMCA of Metro Area",
    address: "400 W Washington Blvd",
    city: "Springfield",
    state: "IL",
    zip: "62704",
    phone: "(217) 555-0303",
    email: "afterschool@ymca-metro.org",
    website: "https://example.com/ymca",
    gradesMin: "K",
    gradesMax: "6",
    ageMin: 5,
    ageMax: 12,
    cost: 150,
    costPeriod: "month",
    scholarshipAvailable: true,
    hours: "3:00 PM – 6:00 PM",
    daysOffered: "Mon–Fri",
    sessionType: "School Year",
    subjects: ["Homework Help", "Sports", "Arts"],
    description: "Safe, structured afterschool environment with homework assistance, physical activities, and enrichment programs. Financial assistance available.",
    indoorOutdoor: "Both",
    transportation: true,
    mealsProvided: true,
    acceptingRegistration: true
  },
  {
    id: 4,
    name: "Tech Wizards Coding Camp",
    type: "Summer Camp",
    organization: "FutureTech Academy",
    address: "888 Innovation Dr",
    city: "Lakewood",
    state: "IL",
    zip: "60014",
    phone: "(815) 555-0404",
    email: "info@futuretech.edu",
    website: "https://example.com/futuretech",
    gradesMin: "4",
    gradesMax: "12",
    ageMin: 9,
    ageMax: 18,
    cost: 400,
    costPeriod: "week",
    scholarshipAvailable: false,
    hours: "9:00 AM – 5:00 PM",
    daysOffered: "Mon–Fri",
    sessionType: "Summer",
    subjects: ["STEM", "Technology", "Coding"],
    description: "Learn Python, web development, game design, and app creation. Beginner to advanced tracks available for all experience levels.",
    indoorOutdoor: "Indoor",
    transportation: false,
    mealsProvided: false,
    acceptingRegistration: true
  },
  {
    id: 5,
    name: "Elite Soccer Academy",
    type: "Summer Camp",
    organization: "Metro Soccer Club",
    address: "1200 Sports Complex Dr",
    city: "Westfield",
    state: "IL",
    zip: "60559",
    phone: "(630) 555-0505",
    email: "soccer@metrosoccer.com",
    website: "https://example.com/metrosoccer",
    gradesMin: "1",
    gradesMax: "12",
    ageMin: 6,
    ageMax: 18,
    cost: 300,
    costPeriod: "week",
    scholarshipAvailable: true,
    hours: "9:00 AM – 3:00 PM",
    daysOffered: "Mon–Fri",
    sessionType: "Summer",
    subjects: ["Sports", "Soccer"],
    description: "Intensive soccer skills training with certified coaches. Sessions for beginners through competitive players.",
    indoorOutdoor: "Outdoor",
    transportation: false,
    mealsProvided: false,
    acceptingRegistration: true
  },
  {
    id: 6,
    name: "Reading & Math Enrichment",
    type: "Afterschool Care",
    organization: "Bright Futures Learning Center",
    address: "75 Elm Street",
    city: "Riverside",
    state: "IL",
    zip: "60546",
    phone: "(708) 555-0606",
    email: "enroll@brightfutures.org",
    website: "https://example.com/brightfutures",
    gradesMin: "K",
    gradesMax: "8",
    ageMin: 5,
    ageMax: 14,
    cost: 200,
    costPeriod: "month",
    scholarshipAvailable: true,
    hours: "3:00 PM – 6:30 PM",
    daysOffered: "Mon–Fri",
    sessionType: "School Year",
    subjects: ["Homework Help", "Math", "Reading"],
    description: "Small-group tutoring and homework help focused on building core reading and math skills. Certified teachers on staff.",
    indoorOutdoor: "Indoor",
    transportation: false,
    mealsProvided: true,
    acceptingRegistration: true
  },
  {
    id: 7,
    name: "Outdoor Adventure Camp",
    type: "Summer Camp",
    organization: "Green Trails Foundation",
    address: "500 Forest Park Rd",
    city: "Lakewood",
    state: "IL",
    zip: "60014",
    phone: "(815) 555-0707",
    email: "adventure@greentrails.org",
    website: "https://example.com/greentrails",
    gradesMin: "3",
    gradesMax: "9",
    ageMin: 8,
    ageMax: 15,
    cost: 350,
    costPeriod: "week",
    scholarshipAvailable: true,
    hours: "8:00 AM – 5:00 PM",
    daysOffered: "Mon–Fri",
    sessionType: "Summer",
    subjects: ["Outdoor Education", "Nature", "Sports"],
    description: "Hiking, kayaking, archery, and environmental education. Campers connect with nature while building confidence and teamwork skills.",
    indoorOutdoor: "Outdoor",
    transportation: false,
    mealsProvided: true,
    acceptingRegistration: true
  },
  {
    id: 8,
    name: "Kids Care After School",
    type: "Afterschool Care",
    organization: "Community School District 42",
    address: "320 Lincoln Ave",
    city: "Westfield",
    state: "IL",
    zip: "60559",
    phone: "(630) 555-0808",
    email: "kidscare@district42.edu",
    website: "https://example.com/district42",
    gradesMin: "K",
    gradesMax: "5",
    ageMin: 5,
    ageMax: 11,
    cost: 125,
    costPeriod: "month",
    scholarshipAvailable: true,
    hours: "3:00 PM – 6:00 PM",
    daysOffered: "Mon–Fri",
    sessionType: "School Year",
    subjects: ["Homework Help", "Arts", "Sports"],
    description: "District-run afterschool program with licensed staff. Homework time, free play, and enrichment activities.",
    indoorOutdoor: "Both",
    transportation: true,
    mealsProvided: true,
    acceptingRegistration: false
  },
  {
    id: 9,
    name: "Young Performers Theater Camp",
    type: "Summer Camp",
    organization: "Spotlight Theater Company",
    address: "220 Stage Ave",
    city: "Springfield",
    state: "IL",
    zip: "62702",
    phone: "(217) 555-0909",
    email: "youth@spotlighttheater.org",
    website: "https://example.com/spotlight",
    gradesMin: "3",
    gradesMax: "12",
    ageMin: 8,
    ageMax: 18,
    cost: 275,
    costPeriod: "week",
    scholarshipAvailable: true,
    hours: "9:00 AM – 4:00 PM",
    daysOffered: "Mon–Fri",
    sessionType: "Summer",
    subjects: ["Arts", "Drama", "Music"],
    description: "Musical theater, acting, voice, and dance. Culminates in a public performance at end of session.",
    indoorOutdoor: "Indoor",
    transportation: false,
    mealsProvided: false,
    acceptingRegistration: true
  },
  {
    id: 10,
    name: "STEM Explorers Club",
    type: "Both",
    organization: "Public Library District",
    address: "1 Library Plaza",
    city: "Springfield",
    state: "IL",
    zip: "62701",
    phone: "(217) 555-1010",
    email: "stem@publiclibrary.org",
    website: "https://example.com/library-stem",
    gradesMin: "K",
    gradesMax: "8",
    ageMin: 5,
    ageMax: 14,
    cost: 0,
    costPeriod: "session",
    scholarshipAvailable: false,
    hours: "4:00 PM – 6:00 PM",
    daysOffered: "Tue & Thu",
    sessionType: "Year-Round",
    subjects: ["STEM", "Science", "Technology", "Coding"],
    description: "FREE library-based program with hands-on science kits, coding projects, and maker activities. No registration required, just show up!",
    indoorOutdoor: "Indoor",
    transportation: false,
    mealsProvided: false,
    acceptingRegistration: true
  },
  {
    id: 11,
    name: "Basketball Skills Camp",
    type: "Summer Camp",
    organization: "Metro Recreation Department",
    address: "700 Recreation Center Blvd",
    city: "Riverside",
    state: "IL",
    zip: "60546",
    phone: "(708) 555-1111",
    email: "recreation@riverside.gov",
    website: "https://example.com/riverside-rec",
    gradesMin: "3",
    gradesMax: "12",
    ageMin: 8,
    ageMax: 18,
    cost: 100,
    costPeriod: "week",
    scholarshipAvailable: true,
    hours: "9:00 AM – 12:00 PM",
    daysOffered: "Mon–Fri",
    sessionType: "Summer",
    subjects: ["Sports", "Basketball"],
    description: "Fundamentals training for all skill levels led by experienced coaches. Morning half-day sessions.",
    indoorOutdoor: "Indoor",
    transportation: false,
    mealsProvided: false,
    acceptingRegistration: true
  },
  {
    id: 12,
    name: "Creative Writing Workshop",
    type: "Afterschool Care",
    organization: "Words Matter Institute",
    address: "45 Author Lane",
    city: "Lakewood",
    state: "IL",
    zip: "60014",
    phone: "(815) 555-1212",
    email: "write@wordsmatter.org",
    website: "https://example.com/wordsmatter",
    gradesMin: "4",
    gradesMax: "10",
    ageMin: 9,
    ageMax: 16,
    cost: 80,
    costPeriod: "month",
    scholarshipAvailable: false,
    hours: "3:30 PM – 5:00 PM",
    daysOffered: "Wed",
    sessionType: "School Year",
    subjects: ["Writing", "Arts", "Reading"],
    description: "Weekly creative writing group exploring fiction, poetry, and journalism. Students share and publish their work in a student literary magazine.",
    indoorOutdoor: "Indoor",
    transportation: false,
    mealsProvided: false,
    acceptingRegistration: true
  }
];
